language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r base_requirements.txt
  - pip install -U pytest pytest-cov coveralls
script:
  - python -m pytest --cov .
after_success:
  - coveralls
